// src/lib/constants.ts
export const DEPARTMENTS = {
  ADMINISTRATION: "ADMINISTRATION",
  HR: "HUMAN_RESOURCES",
  PROJECTS: "PROJECTS",
  OPERATIONS: "OPERATIONS",
  FINANCE: "FINANCE",
  INVENTORY: "INVENTORY",
} as const;

export const MODULES = {
  CONTACTS: "CONTACT_MANAGEMENT",
  PROJECTS: "PROJECT_MANAGEMENT",
  HR: "HR_MANAGEMENT",
  BI: "BUSINESS_INTELLIGENCE",
  ACCOUNTS: "ACCOUNT_MANAGEMENT",
  SUPPLY_CHAIN: "SUPPLY_CHAIN",
  INVENTORY: "MATERIALS_INVENTORY",
  ACCESS: "ACCESS_CONTROL",
  OFFICE: "OFFICE_ADMIN",
  SAFETY: "HEALTH_SAFETY",
  SETTINGS: "SETTINGS",
} as const;

export const DEPARTMENT_MODULES = {
  [DEPARTMENTS.ADMINISTRATION]: [
    MODULES.ACCESS,
    MODULES.SETTINGS,
    MODULES.OFFICE,
  ],
  [DEPARTMENTS.HR]: [MODULES.HR, MODULES.SAFETY],
  [DEPARTMENTS.PROJECTS]: [MODULES.PROJECTS, MODULES.CONTACTS],
  [DEPARTMENTS.OPERATIONS]: [MODULES.SUPPLY_CHAIN],
  [DEPARTMENTS.FINANCE]: [MODULES.ACCOUNTS, MODULES.BI],
  [DEPARTMENTS.INVENTORY]: [MODULES.INVENTORY],
} as const;
